import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Terms \u2014 Futures Church",
  description:
    "Terms of use for Futures Church\u2019s website and the Selah pastoral companion.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms"
      subtitle="The agreement. In plain English."
      updated="Effective 19 April 2026"
      sections={[
        {
          h: "Who we are",
          body: [
            "\u201cFutures\u201d, \u201cFutures Church\u201d, \u201cwe\u201d, or \u201cus\u201d refers to the Futures Church network, led globally by Ashley and Jane Evans. By using this website or Selah, you agree to these terms.",
          ],
        },
        {
          h: "What Selah is \u2014 and isn\u2019t",
          body: [
            "Selah is an AI-powered pastoral companion. It is not a licensed therapist, not a medical provider, not a lawyer, not a financial adviser, and not an emergency service.",
            "Selah\u2019s responses are generated by a language model grounded in Scripture and a curated corpus of biblical teaching. Responses are thoughtful, but they are not infallible and should never be used as a substitute for professional care.",
            "Do not rely on Selah for medical, legal, or financial decisions.",
          ],
        },
        {
          h: "Crisis and safety",
          body: [
            "If you are in immediate danger, or thinking about hurting yourself or someone else, call your local emergency number now. In the US: 988. In Australia: Lifeline 13 11 14. In the UK: Samaritans 116 123.",
            "Selah will point you to these resources if its safety classifier detects crisis language, but it is not a substitute for them and it does not call anyone on your behalf.",
          ],
        },
        {
          h: "Your account and membership",
          body: [
            "Founding-member and standard memberships are processed by Stripe. You can cancel at any time from your account page or by emailing hello@futures.church \u2014 no phone call, no friction.",
            "Founding-member pricing is locked for the life of your continuous subscription. If you cancel and resubscribe later, the current standard price applies.",
            "We may suspend or close an account that uses Selah for abusive content, automated scraping, attempts to extract the system prompt, or anything illegal. We\u2019ll tell you why before we do.",
          ],
        },
        {
          h: "Refunds",
          body: [
            "If Selah isn\u2019t right for you, email hello@futures.church within 14 days of your first charge and we\u2019ll refund it. No forms, no script.",
          ],
        },
        {
          h: "Your content",
          body: [
            "Anything you submit on signup forms (your name, your email, the optional \u201cone thing on your heart\u201d note) stays between you and us. We don\u2019t publish it, share it, or sell it.",
            "Conversations with Selah aren\u2019t stored at all \u2014 see the privacy policy for the full zero-retention covenant.",
          ],
        },
        {
          h: "Intellectual property",
          body: [
            "The Futures Church name, marks, and the distinct design of this site belong to Futures Church. Scripture in the public domain belongs to no one. Commentary we quote is cited and used under fair use for educational and pastoral purposes.",
            "You\u2019re welcome to save, copy, or share your own Selah conversations however you like \u2014 they\u2019re yours.",
          ],
        },
        {
          h: "Disclaimers",
          body: [
            "Selah and this website are provided \u201cas is.\u201d We do our best to keep them accurate, safe, and up, but we don\u2019t guarantee they\u2019ll be error-free or continuously available.",
            "To the extent the law allows, Futures Church isn\u2019t liable for indirect or consequential loss arising from use of this site or of Selah. The direct liability cap is whatever you\u2019ve paid us in the last 12 months.",
          ],
        },
        {
          h: "Governing law",
          body: [
            "These terms are governed by the laws of South Australia. If there\u2019s a dispute we can\u2019t resolve by conversation, the courts of South Australia have jurisdiction.",
          ],
        },
        {
          h: "Changes",
          body: [
            "If we materially change these terms, we\u2019ll email everyone on our list before the change takes effect and update the date at the top.",
          ],
        },
        {
          h: "Contact",
          body: ["hello@futures.church \u2014 a real person reads it."],
        },
      ]}
    />
  );
}
