#!/usr/bin/env bash
# scripts/setup-portal.sh
#
# Idempotent one-shot setup for the intake/events/photo portal.
#   • Generates INTAKE_ADMIN_SECRET (if missing) and writes it to .env.local
#   • Asks once for INTAKE_ADMIN_PASSWORD (if missing) and writes it
#   • Concatenates every unapplied migration into supabase/_apply.sql for a single paste
#   • Prints next steps
#
# Safe to re-run. Existing values in .env.local are never overwritten.

set -euo pipefail

# Resolve repo root from this script's location (so it runs from anywhere).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env.local"
APPLY_FILE="$REPO_ROOT/supabase/_apply.sql"
MIGRATIONS_DIR="$REPO_ROOT/supabase/migrations"

dim()  { printf "\033[2m%s\033[0m\n" "$1"; }
ok()   { printf "\033[32m✓\033[0m %s\n" "$1"; }
warn() { printf "\033[33m!\033[0m %s\n" "$1"; }
hdr()  { printf "\n\033[1m%s\033[0m\n" "$1"; }

touch "$ENV_FILE"

env_has() { grep -qE "^${1}=" "$ENV_FILE" 2>/dev/null; }
env_get() { grep -E "^${1}=" "$ENV_FILE" | head -1 | cut -d= -f2-; }

# ── Secret ──────────────────────────────────────────────────────────────────
hdr "1. Admin session secret"
if env_has INTAKE_ADMIN_SECRET && [ -n "$(env_get INTAKE_ADMIN_SECRET)" ]; then
  ok "INTAKE_ADMIN_SECRET already set in .env.local — leaving as-is."
else
  SECRET="$(openssl rand -hex 32)"
  printf "INTAKE_ADMIN_SECRET=%s\n" "$SECRET" >> "$ENV_FILE"
  ok "Generated and wrote a 64-char admin session secret to .env.local."
fi

# ── Password ────────────────────────────────────────────────────────────────
hdr "2. Admin password"
if env_has INTAKE_ADMIN_PASSWORD && [ -n "$(env_get INTAKE_ADMIN_PASSWORD)" ]; then
  ok "INTAKE_ADMIN_PASSWORD already set in .env.local — leaving as-is."
else
  echo "Pick a shared password for the admin dashboard."
  echo "(2-3 admins will share this. Anything memorable is fine; not high-security.)"
  while true; do
    printf "  Password: "
    read -rs PW
    echo
    if [ ${#PW} -lt 6 ]; then
      warn "Pick at least 6 characters."
      continue
    fi
    printf "  Confirm:  "
    read -rs PW2
    echo
    if [ "$PW" != "$PW2" ]; then
      warn "Didn't match. Try again."
      continue
    fi
    break
  done
  printf "INTAKE_ADMIN_PASSWORD=%s\n" "$PW" >> "$ENV_FILE"
  ok "Wrote INTAKE_ADMIN_PASSWORD to .env.local."
fi

# ── Migrations ──────────────────────────────────────────────────────────────
hdr "3. Migrations bundle"
if [ ! -d "$MIGRATIONS_DIR" ]; then
  warn "No supabase/migrations folder. Skipping bundle."
else
  cat /dev/null > "$APPLY_FILE"
  printf -- "-- Combined intake/events/photo-repository migrations\n" >> "$APPLY_FILE"
  printf -- "-- Generated by scripts/setup-portal.sh on %s\n" "$(date)" >> "$APPLY_FILE"
  printf -- "-- Idempotent where possible. Safe to re-run.\n\n" >> "$APPLY_FILE"
  for f in "$MIGRATIONS_DIR"/0002_intake.sql "$MIGRATIONS_DIR"/0003_events.sql "$MIGRATIONS_DIR"/0004_photo_repository.sql; do
    if [ -f "$f" ]; then
      printf -- "\n-- ─── %s ───\n" "$(basename "$f")" >> "$APPLY_FILE"
      cat "$f" >> "$APPLY_FILE"
      printf "\n" >> "$APPLY_FILE"
    fi
  done
  ok "Wrote combined SQL → supabase/_apply.sql"
fi

# ── Sanity-check Supabase env ───────────────────────────────────────────────
hdr "4. Supabase config check"
MISSING=()
for k in NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY; do
  if ! env_has "$k" || [ -z "$(env_get "$k")" ]; then
    MISSING+=("$k")
  fi
done
if [ ${#MISSING[@]} -eq 0 ]; then
  ok "Supabase URL + anon key + service role key all present."
else
  warn "Missing in .env.local: ${MISSING[*]}"
  echo "    Add them before pushing migrations. Find them in your Supabase project → Settings → API."
fi

# ── Done ────────────────────────────────────────────────────────────────────
hdr "Done. Two things left."
echo
echo "  ① Apply the migrations to Supabase. Easiest path:"
echo "      • Open your Supabase dashboard → SQL Editor → New query"
echo "      • Paste the contents of:  supabase/_apply.sql"
echo "      • Click Run."
echo
echo "    (Or, if you have the supabase CLI installed:  supabase db push  )"
echo
echo "  ② Restart the dev server and visit:"
echo "      http://localhost:3000/intake/admin/login"
echo "      Sign in with the password you set above."
echo "      Then click 'Campus links · seed & copy' to generate the 25 pastor links."
echo
ok "Setup complete."
